# Numpy练习

In [1]:
import numpy as np

In [2]:
print (np.__version__ )          #查看numpy版本和配置信息；

1.13.1


In [3]:
z=np.zeros((2,3))                #创建零向量，zeros函数；
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [4]:
z[1,2] = 1 
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [5]:
z.shape

(2, 3)

In [6]:
z = np.arange(1,101)                #生成从1到100的数组；前闭后开；
z

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
z.shape

(100,)

In [8]:
z = np.arange(9).reshape(3,3) 
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
nz = np.nonzero([1,2,3,0,0,4,0])          #nonzero函数，寻找非0元素的下标
nz

(array([0, 1, 2, 5], dtype=int64),)

In [10]:
z=np.random.random((10,10))      #min()、max()函数

In [11]:
z

array([[ 0.32684838,  0.38770295,  0.33968293,  0.3424737 ,  0.07561491,
         0.25146977,  0.17560169,  0.99566585,  0.88165774,  0.18504057],
       [ 0.27058358,  0.41310897,  0.82512036,  0.74484961,  0.50623851,
         0.89494032,  0.10332382,  0.14708797,  0.84768699,  0.11380937],
       [ 0.84850839,  0.33048464,  0.80196266,  0.39489677,  0.53890661,
         0.51339261,  0.28837649,  0.99940904,  0.45643414,  0.57019041],
       [ 0.98201835,  0.04446732,  0.52429751,  0.03853288,  0.1773176 ,
         0.87629532,  0.28720068,  0.45338776,  0.04969956,  0.58804825],
       [ 0.73422371,  0.73171214,  0.93607786,  0.57637608,  0.06429117,
         0.33611386,  0.70766999,  0.79585928,  0.24594097,  0.4706178 ],
       [ 0.74332383,  0.83242141,  0.50737107,  0.67811313,  0.47852859,
         0.97232966,  0.4401773 ,  0.34719731,  0.26207992,  0.4723847 ],
       [ 0.23576606,  0.65623519,  0.44480502,  0.37607237,  0.49899472,
         0.49556481,  0.62799889,  0.60895992

In [12]:
zmin,zmax = z.min(),z.max()    #unpacked
zmin, zmax

(0.0045892123810477026, 0.99940904460224689)

In [13]:
z = np.random.randn(5,5)
z

array([[-0.01240812,  0.54553773,  0.0770298 ,  0.6460162 ,  1.81836902],
       [-0.7295535 , -2.0992206 ,  0.55524641, -2.30064629, -0.77276183],
       [-1.00392353, -1.02737629,  0.07730328,  0.45230371, -0.66509166],
       [-0.23382409, -2.17469317,  0.13431039,  1.76896403,  0.95942732],
       [ 0.88184983, -1.11169278, -0.34464913, -1.23931026, -2.30755044]])

In [14]:
#标准化,多因子策略；
zmax,zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[ 0.55627415,  0.6915036 ,  0.57795123,  0.71585659,  1.        ],
       [ 0.38245946,  0.05049295,  0.6938567 ,  0.00167336,  0.37198705],
       [ 0.31596034,  0.31027609,  0.57801752,  0.66890645,  0.39808309],
       [ 0.50260951,  0.03220065,  0.59183434,  0.9880257 ,  0.79181811],
       [ 0.77301564,  0.28984028,  0.47574882,  0.25890961,  0.        ]])

In [15]:
#矩阵点乘
z=np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [16]:
Z = np.zeros((5,5))              
#矩阵相加，5*5矩阵+1*5的向量，相当于每一行都加上1*5矩阵
Z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
Z += np.arange(5)      #broadcasting;
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [18]:
Z = np.linspace(0,10,11)
Z

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [19]:
Z = np.random.random(10)           
#sort函数。调用random模块中的random函数生成10个随机数，然后sort排序
Z

array([ 0.48519741,  0.50045399,  0.60620404,  0.70045174,  0.62845143,
        0.3529416 ,  0.46124793,  0.20503014,  0.44213375,  0.12152642])

In [20]:
Z.sort()
Z

array([ 0.12152642,  0.20503014,  0.3529416 ,  0.44213375,  0.46124793,
        0.48519741,  0.50045399,  0.60620404,  0.62845143,  0.70045174])

In [21]:
Z = np.random.random(30)             #mean函数，求平均值
Z

array([ 0.12117742,  0.44137015,  0.41499283,  0.32169803,  0.78264714,
        0.12862691,  0.42681858,  0.3157775 ,  0.90650605,  0.54109245,
        0.78728141,  0.9317153 ,  0.5680091 ,  0.86506352,  0.05090905,
        0.09970275,  0.01901634,  0.72448481,  0.54527251,  0.74793562,
        0.9537344 ,  0.59922599,  0.76821998,  0.31595371,  0.30946956,
        0.40768575,  0.64153503,  0.38275643,  0.88654987,  0.39219734])

In [22]:
Z.mean()

0.51324751765572496

In [23]:
Z = np.random.rand(10)             
#获取数组中最大值/最小值对应的下标，argmax()、argmin()函数,产生0-1的随机数
Z

array([ 0.02381595,  0.1619362 ,  0.84481657,  0.23277963,  0.51495489,
        0.33883899,  0.95349526,  0.34552359,  0.39638592,  0.28971898])

In [24]:
Z.argmax()

6

In [25]:
Z.argmin() 

0

In [26]:
#找出数组中与给定值最接近的数
Z = np.array([[0,1,2,3],[7,6,5,4]])  
z=5.1 
np.abs(Z - z).argmin()

6

In [27]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a.dot(b)

20

In [28]:
a * b                   #注意，a*b是元素间的乘法，不是点乘；

array([ 2,  6, 12])

In [29]:
b.T

array([2, 3, 4])

In [30]:
c = np.asmatrix(a) * np.asmatrix(b).T    #把Ndarray类型转换成matrix：np.asmatrix;
c

matrix([[20]])

In [31]:
c.shape

(1, 1)

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a.sum()

45

In [34]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [35]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
b = np.where(a < 50)
b

(array([0, 1, 2, 3, 4], dtype=int64),)

In [37]:
b = a[np.where(a < 50)]
b

array([ 0, 10, 20, 30, 40])

In [38]:
b = a[[0, 1, 2, 3, 4]]
b

array([ 0, 10, 20, 30, 40])

In [39]:
a = np.array([1,2,3])         #使用hstack 横向拼接   使用vstack 纵向拼接
b = np.array([4,5,6])
c = np.hstack([a,b])
d = np.vstack([a,b])

In [40]:
c

array([1, 2, 3, 4, 5, 6])

In [41]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [43]:
np.append(a,[1,2,3,4])     #预期一致；

array([1, 2, 3, 4, 1, 2, 3, 4])

In [44]:
a = [1, 2, 3, 4]

In [45]:
a.append([1, 2, 3, 4])
a

[1, 2, 3, 4, [1, 2, 3, 4]]

In [46]:
a.extend([1, 2, 3, 4])
a

[1, 2, 3, 4, [1, 2, 3, 4], 1, 2, 3, 4]

In [47]:
np.sign(np.random.randn(5))                                     #获得正负号情况

array([-1., -1., -1.,  1.,  1.])

In [48]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [49]:
b = a.tolist()                                  #重要，ndarray转换为list
a

array([1, 2, 3, 4])

In [50]:
type(b)                

list

In [51]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.cumsum()                               #计算累积收益,连续return计算的情况下；

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [53]:
a.cumprod()                             #计算累积收益，离散return计算的情况下；

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [54]:
a = np.array([0.01, 0.02, -0.02, -0.04, 0.06, -0.01])
a

array([ 0.01,  0.02, -0.02, -0.04,  0.06, -0.01])

In [55]:
a= np.cumprod(a + 1)

In [56]:
a

array([ 1.01      ,  1.0302    ,  1.009596  ,  0.96921216,  1.02736489,
        1.01709124])