# Python语法基础知识——模块

### 1. Importing

In [1]:
log(10)

NameError: name 'log' is not defined

In [2]:
import math

In [3]:
math.log(10)

2.302585092994046

In [4]:
math.sqrt(2)

1.4142135623730951

In [10]:
from math import log,sqrt,sin,cos

In [6]:
math.log(10)

2.302585092994046

In [7]:
log(10)

2.302585092994046

In [9]:
sqrt(2)

1.4142135623730951

In [11]:
from math import *           #不推荐，冲突问题；

In [12]:
sin(10)

-0.5440211108893698

In [13]:
cos(10)

-0.8390715290764524

In [ ]:
math.sqrt()

In [14]:
import numpy as np
import pandas as pd

In [15]:
range(5)

range(0, 5)

In [16]:
for i in range(5):
    print(i)

0
1
2
3
4


In [17]:
a = np.arange(10)        #range——>python
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = arange(10)

NameError: name 'arange' is not defined

#### 1.1 From…import.... 语句

Python 的 from 语句让你从模块中导入一个指定的部分到当前命名空间中。

In [20]:
from numpy import exp, arange

In [21]:
a = arange(10)        #不建议；
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
exp(a)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

#### 1.2 From…import * 语句

把一个模块的所有内容全都导入到当前的命名空间也是可行的，只需使用如下声明：

In [24]:
from math import *
sqrt(2)

1.4142135623730951

In [25]:
exp(10)

22026.465794806718

#### 1.3 练习

In [ ]:
import numpy as np

In [ ]:
np.  # tab 

In [26]:
import support

In [27]:
support.print_func('Quantative Finance')

Hello,Quantative Finance


In [28]:
support.print_func('jihuicheng')

Hello,jihuicheng


In [29]:
import datetime

In [31]:
a = datetime.datetime.now()
a

datetime.datetime(2017, 7, 25, 15, 28, 36, 567611)

In [32]:
from datetime import datetime

In [34]:
b = datetime.now()
b

datetime.datetime(2017, 7, 25, 15, 30, 2, 428580)

In [35]:
c = datetime.datetime.now()

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

In [ ]:
datetime.